[workspace.package]
authors = ["forestaa <t.daichi.3@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace]
members = ["client", "server"]
resolver = "2"

[profile.release.package.passkey-demo-client]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
